//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YellEat.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ye_Order
    {
        public Ye_Order()
        {
            this.Ye_OrderDetail = new HashSet<Ye_OrderDetail>();
        }
    
        public int OrderID { get; set; }
        public int UserID { get; set; }
        public int ShopID { get; set; }
        public string OrderSN { get; set; }
        public string OrderDesc { get; set; }
        public System.DateTime OrderCreateTime { get; set; }
        public Nullable<System.DateTime> OrderCheckTime { get; set; }
        public Nullable<System.DateTime> OrderPayTime { get; set; }
        public Nullable<decimal> UnitCouponCost { get; set; }
        public Nullable<int> ShopCouponID { get; set; }
        public decimal TotalPrice { get; set; }
        public int OrderStatus { get; set; }
        public string Receiver { get; set; }
        public string ReceiverMobile { get; set; }
        public string ReceiveAddress { get; set; }
        public bool IsUserDeleted { get; set; }
        public bool IsShopDeleted { get; set; }
        public decimal Tax { get; set; }
        public bool IsReminded { get; set; }
    
        public virtual ICollection<Ye_OrderDetail> Ye_OrderDetail { get; set; }
    }
}
