//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YellEat.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ye_Product
    {
        public int ProductID { get; set; }
        public int ProductTypeID { get; set; }
        public int ShopID { get; set; }
        public string ProductNo { get; set; }
        public string ProductName { get; set; }
        public string ProductDesc { get; set; }
        public System.DateTime CreateDate { get; set; }
        public bool IsUpShelf { get; set; }
        public int RecommendLevel { get; set; }
        public int Clicks { get; set; }
        public string ProductImage { get; set; }
        public int UnitId { get; set; }
        public decimal Discount { get; set; }
        public decimal Price { get; set; }
    }
}
