//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YellEat.Model
{
    using System;
    using System.Collections.Generic;
    [Serializable]
    public partial class Ye_Shop
    {
        public int ShopID { get; set; }
        public string ShopAccount { get; set; }
        public string ShopPassword { get; set; }
        public System.DateTime RegisterTime { get; set; }
        public System.DateTime LastLoginTime { get; set; }
        public string ShopName { get; set; }
        public string ShopAddress { get; set; }
        public string ShopZip { get; set; }
        public string ShopMobile { get; set; }
        public string ShopEmail { get; set; }
        public string ShopQQ { get; set; }
        public string ShopFax { get; set; }
        public decimal Longitude { get; set; }
        public decimal Latitude { get; set; }
        public string ShopMainImg { get; set; }
        public string ShopLogoImg { get; set; }
        public string ShopQRCodeImg { get; set; }
        public string ShopDesc { get; set; }
        public int Clicks { get; set; }
        public int Rank { get; set; }
        public string DeliveryTime { get; set; }
        public decimal DeliveryMinPrice { get; set; }
        public int RecommendLevel { get; set; }
        public bool IsChecked { get; set; }
        public int OpeningBeginMinute { get; set; }
        public int OpeningEndMinute { get; set; }
        public Nullable<int> OpeningBeginMinute2 { get; set; }
        public Nullable<int> OpeningEndMinute2 { get; set; }
    }
}
