//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YellEat.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ye_ShopFeedback
    {
        public int ShopFeedbackID { get; set; }
        public int ShopId { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string FeedbackContent { get; set; }
        public bool IsHandled { get; set; }
        public string HandleAnswer { get; set; }
        public System.DateTime HandledTime { get; set; }
        public bool IsShopDeleted { get; set; }
        public bool IsAdminDeleted { get; set; }
    }
}
